# Dependencies
markdown:         redcarpet
redcarpet:
  extensions: ["tables"]

pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Oleksandr "Sasha" Sochka
tagline:          'Programming and stuff'
url:              http://www.sochka.github.io
shorturl:         socka.github.io

author:
  name:           'Oleksandr "Sasha" Sochka'
  url:            https://facebook.com/oleksandr.sochka

paginate:         1

# Custom vars
# version:          1.0.0

github:
  repo:           github.com/sochka/sochka.github.io

# This is the list of pages to incldue in the header of the website.
pages_list:
  About: '/about/'
  Archive: '/archive/'
  Feed: '/atom.xml'
